version: '3.8'
services:
  terraform:
    build:
      context: .
      dockerfile: terraform.dockerfile
    volumes:
      - $PWD:/work
    working_dir: /work
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
